name: funny comment
on:
  issues:
    types: [opened]
    
jobs:
  comment: 
    if: github.event_name == ‘issues’
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - id: FunnyComment
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	  GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
	  comment_type: ‘gif’
